language: node_js
node_js: node
before_install:
- npm install -g npm
script:
- npm install
deploy:
  provider: heroku
  api_key:
    secure: jiLJqIV5IXcB4pOF+u9kotUokVRyb449B2lv3VdHEQIJHYLV3c6gaULpbiqoUXOYt6sAfKnktU/YF+l+kITB462S2dDJ/R7rp8zvg6sZC7hvPIAotNQVY+0DhC9X7vG4lTW0zR9oGoGUSDUSlY9IcBpV/gPPhraNaWEheaiJZ1yorMGV2ueQ8u5vw4yZ7XO0+w3hNYzdkJUjDTZh78PRsIfX47cQD566aKNDr94JpEgcidgd2LsWwH8ZStC2JHARJzwXVbpFcGdbBFJZG7q/IFC2+wFCia8Wnwtd45NXG0Q1fWsUmFrhJ5gSg06jHq4kENr3oTJ/QDn6D8r+BmO83CmXV3/P+dZ76v09dwOn0cCYMcXoA59TCbUGxXrOYb1dKu5XQxoRTtIchl1JruNEK55XrvJDm2Mxfx2NTdTk9bzQUJlx/tS5E9ER/RbXoklnmebICCKK869aoeH4psRi1VIWzte0CzG7ttji/Z9E4fYW1DMd1okPaaI+nzX1lO68LyC5i7X0Da4llu4ZS5UlfgHONh4+Lc0UXnSDxbnaiKwXoY9qicKJNX6tvuA4PzhuKjB/Fgs0uGOS2D8RSAWrLmq8wg9hTdYhyOa7cQfPG/Bbz+cpOQVyT70xKJVhQaoA2n/qedyJqap9gdiz+XOwkQ9qVJpE783TwMbIbZQtma0=
  app: rocky-thicket-69982
  on:
    repo: spikeburton/emaily
