language: node_js
node_js: node
before_install:
- npm install -g npm
script:
- npm install
deploy:
  provider: heroku
  api_key:
    secure: i9+L5lrV32g+y+Hje7y9rmM8r+Hq6O7Nc4yEj9nipPSaJ+zN74AJZL4dESGKImFFFexfqOmCwmc7SY1gIBYBO+6dvcYl1lH7X3Fx+BoFwdUidrLMWY5TiGAwvGZr2t23/KphpI+xiyxYOCFUwam1Qq8SF9ZtNwk4wgn2ff0PfmNpa072DaY/u0amtn1JI/Yj8Z/Lhoa3G/3/kU8w1dESzEthOcKtrBUaZBtm7hmpEQ8n64XMVyE+MRNK5ovgzkM9+6PlAK9riJANnC9t9eO17BiGNqVIGCs4vsiJmw25wOA8H5x88o8LZ9zOG5+4hJtxRYatTPuD6+x9n3o/rB5TvjdsHO6PpKK+EU5qVjlUr/x+eQ1Tf4QUo7dlws6UrTz+TI5In19AdUMnshDgenWpb2RAuQoGmxHQv9+Pu684zz9D3y/7mnkYtVyBS6GFUIibWRe9avM1ywg7lJw1x8hhF44P1MLIkYutlXp55gLBsqJ6qA4r2DlYBnBy/4VKwBDh4FZ6uhWCFxtOXFuMYCn2mt4DH95+eZJNbTjQnOt/GavDaytfCQcD7pdfjEzdDVO7NGfsdHlcuEnMqk4kuOWp/5g8an4rX8f9tjpC69ahHFWJuV14cVQKid4+ZxhFCxeHWbo1kJtO9R1AzldSd9+Bolh8MufiuzqumcXzz6vu80Q=
  app: rocky-thicket-69982
  on:
    repo: spikeburton/emaily
